// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENTTIMESTAMP_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_CLIENTTIMESTAMP_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct ClientTimestampResult;
struct ClientTimestampResultBuilder;

struct ClientTimestampResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientTimestampResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct ClientTimestampResultBuilder {
  typedef ClientTimestampResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(ClientTimestampResult::VT_TIMESTAMP, timestamp, 0);
  }
  explicit ClientTimestampResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientTimestampResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientTimestampResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientTimestampResult> CreateClientTimestampResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0) {
  ClientTimestampResultBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  return builder_.Finish();
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_CLIENTTIMESTAMP_ANTICHEAT_H_
