// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EVENT_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_EVENT_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct KernelModuleLoad;
struct KernelModuleLoadBuilder;

struct Event;
struct EventBuilder;

struct EventBatch;
struct EventBatchBuilder;

enum EventBody : uint8_t {
  EventBody_NONE = 0,
  EventBody_KernelModuleLoad = 1,
  EventBody_MIN = EventBody_NONE,
  EventBody_MAX = EventBody_KernelModuleLoad
};

inline const EventBody (&EnumValuesEventBody())[2] {
  static const EventBody values[] = {
    EventBody_NONE,
    EventBody_KernelModuleLoad
  };
  return values;
}

inline const char * const *EnumNamesEventBody() {
  static const char * const names[3] = {
    "NONE",
    "KernelModuleLoad",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventBody(EventBody e) {
  if (::flatbuffers::IsOutRange(e, EventBody_NONE, EventBody_KernelModuleLoad)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventBody()[index];
}

template<typename T> struct EventBodyTraits {
  static const EventBody enum_value = EventBody_NONE;
};

template<> struct EventBodyTraits<Anticheat::KernelModuleLoad> {
  static const EventBody enum_value = EventBody_KernelModuleLoad;
};

template <bool B = false>
bool VerifyEventBody(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventBody type);
template <bool B = false>
bool VerifyEventBodyVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct KernelModuleLoad FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KernelModuleLoadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE_ADDRESS = 4,
    VT_SIZE = 6,
    VT_NAME = 8
  };
  uint64_t base_address() const {
    return GetField<uint64_t>(VT_BASE_ADDRESS, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_BASE_ADDRESS, 8) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct KernelModuleLoadBuilder {
  typedef KernelModuleLoad Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base_address(uint64_t base_address) {
    fbb_.AddElement<uint64_t>(KernelModuleLoad::VT_BASE_ADDRESS, base_address, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(KernelModuleLoad::VT_SIZE, size, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(KernelModuleLoad::VT_NAME, name);
  }
  explicit KernelModuleLoadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KernelModuleLoad> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KernelModuleLoad>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KernelModuleLoad> CreateKernelModuleLoad(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t base_address = 0,
    uint32_t size = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  KernelModuleLoadBuilder builder_(_fbb);
  builder_.add_base_address(base_address);
  builder_.add_name(name);
  builder_.add_size(size);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KernelModuleLoad> CreateKernelModuleLoadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t base_address = 0,
    uint32_t size = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Anticheat::CreateKernelModuleLoad(
      _fbb,
      base_address,
      size,
      name__);
}

struct Event FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  Anticheat::EventBody body_type() const {
    return static_cast<Anticheat::EventBody>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const Anticheat::KernelModuleLoad *body_as_KernelModuleLoad() const {
    return body_type() == Anticheat::EventBody_KernelModuleLoad ? static_cast<const Anticheat::KernelModuleLoad *>(body()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyEventBody(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Anticheat::KernelModuleLoad *Event::body_as<Anticheat::KernelModuleLoad>() const {
  return body_as_KernelModuleLoad();
}

struct EventBuilder {
  typedef Event Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(Anticheat::EventBody body_type) {
    fbb_.AddElement<uint8_t>(Event::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Event::VT_BODY, body);
  }
  explicit EventBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Event> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Event>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Event> CreateEvent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Anticheat::EventBody body_type = Anticheat::EventBody_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  EventBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

struct EventBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventBatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Event>> *events() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Event>> *>(VT_EVENTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_EVENTS) &&
           verifier.VerifyVector(events()) &&
           verifier.VerifyVectorOfTables(events()) &&
           verifier.EndTable();
  }
};

struct EventBatchBuilder {
  typedef EventBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_events(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Event>>> events) {
    fbb_.AddOffset(EventBatch::VT_EVENTS, events);
  }
  explicit EventBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventBatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventBatch> CreateEventBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Event>>> events = 0) {
  EventBatchBuilder builder_(_fbb);
  builder_.add_events(events);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventBatch> CreateEventBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Anticheat::Event>> *events = nullptr) {
  auto events__ = events ? _fbb.CreateVector<::flatbuffers::Offset<Anticheat::Event>>(*events) : 0;
  return Anticheat::CreateEventBatch(
      _fbb,
      events__);
}

template <bool B>
inline bool VerifyEventBody(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventBody type) {
  switch (type) {
    case EventBody_NONE: {
      return true;
    }
    case EventBody_KernelModuleLoad: {
      auto ptr = reinterpret_cast<const Anticheat::KernelModuleLoad *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyEventBodyVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEventBody(
        verifier,  values->Get(i), types->GetEnum<EventBody>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_EVENT_ANTICHEAT_H_
