// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EXAMPLECHECK_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_EXAMPLECHECK_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct ExampleCheckResult;
struct ExampleCheckResultBuilder;

struct ExampleCheckResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExampleCheckResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4,
    VT_STATUS = 6
  };
  uint64_t value() const {
    return GetField<uint64_t>(VT_VALUE, 0);
  }
  uint32_t status() const {
    return GetField<uint32_t>(VT_STATUS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_VALUE, 8) &&
           VerifyField<uint32_t>(verifier, VT_STATUS, 4) &&
           verifier.EndTable();
  }
};

struct ExampleCheckResultBuilder {
  typedef ExampleCheckResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(uint64_t value) {
    fbb_.AddElement<uint64_t>(ExampleCheckResult::VT_VALUE, value, 0);
  }
  void add_status(uint32_t status) {
    fbb_.AddElement<uint32_t>(ExampleCheckResult::VT_STATUS, status, 0);
  }
  explicit ExampleCheckResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExampleCheckResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExampleCheckResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExampleCheckResult> CreateExampleCheckResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t value = 0,
    uint32_t status = 0) {
  ExampleCheckResultBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_status(status);
  return builder_.Finish();
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_EXAMPLECHECK_ANTICHEAT_H_
