// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HANDLESTRIP_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_HANDLESTRIP_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct StrippedHandleInfo;
struct StrippedHandleInfoBuilder;

struct HandleStripResult;
struct HandleStripResultBuilder;

struct StrippedHandleInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StrippedHandleInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PROCESS_ID = 4,
    VT_SOURCE_PROCESS_ID = 6,
    VT_ACCESS = 8
  };
  uint64_t target_process_id() const {
    return GetField<uint64_t>(VT_TARGET_PROCESS_ID, 0);
  }
  uint64_t source_process_id() const {
    return GetField<uint64_t>(VT_SOURCE_PROCESS_ID, 0);
  }
  uint32_t access() const {
    return GetField<uint32_t>(VT_ACCESS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TARGET_PROCESS_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_SOURCE_PROCESS_ID, 8) &&
           VerifyField<uint32_t>(verifier, VT_ACCESS, 4) &&
           verifier.EndTable();
  }
};

struct StrippedHandleInfoBuilder {
  typedef StrippedHandleInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_process_id(uint64_t target_process_id) {
    fbb_.AddElement<uint64_t>(StrippedHandleInfo::VT_TARGET_PROCESS_ID, target_process_id, 0);
  }
  void add_source_process_id(uint64_t source_process_id) {
    fbb_.AddElement<uint64_t>(StrippedHandleInfo::VT_SOURCE_PROCESS_ID, source_process_id, 0);
  }
  void add_access(uint32_t access) {
    fbb_.AddElement<uint32_t>(StrippedHandleInfo::VT_ACCESS, access, 0);
  }
  explicit StrippedHandleInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StrippedHandleInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StrippedHandleInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StrippedHandleInfo> CreateStrippedHandleInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t target_process_id = 0,
    uint64_t source_process_id = 0,
    uint32_t access = 0) {
  StrippedHandleInfoBuilder builder_(_fbb);
  builder_.add_source_process_id(source_process_id);
  builder_.add_target_process_id(target_process_id);
  builder_.add_access(access);
  return builder_.Finish();
}

struct HandleStripResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HandleStripResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HANDLES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::StrippedHandleInfo>> *handles() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::StrippedHandleInfo>> *>(VT_HANDLES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HANDLES) &&
           verifier.VerifyVector(handles()) &&
           verifier.VerifyVectorOfTables(handles()) &&
           verifier.EndTable();
  }
};

struct HandleStripResultBuilder {
  typedef HandleStripResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_handles(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::StrippedHandleInfo>>> handles) {
    fbb_.AddOffset(HandleStripResult::VT_HANDLES, handles);
  }
  explicit HandleStripResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HandleStripResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HandleStripResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HandleStripResult> CreateHandleStripResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::StrippedHandleInfo>>> handles = 0) {
  HandleStripResultBuilder builder_(_fbb);
  builder_.add_handles(handles);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HandleStripResult> CreateHandleStripResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Anticheat::StrippedHandleInfo>> *handles = nullptr) {
  auto handles__ = handles ? _fbb.CreateVector<::flatbuffers::Offset<Anticheat::StrippedHandleInfo>>(*handles) : 0;
  return Anticheat::CreateHandleStripResult(
      _fbb,
      handles__);
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_HANDLESTRIP_ANTICHEAT_H_
