// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_KERNELMODULES_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_KERNELMODULES_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct KernelModule;
struct KernelModuleBuilder;

struct KernelModuleList;
struct KernelModuleListBuilder;

struct KernelModule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KernelModuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE_ADDRESS = 4,
    VT_SIZE = 6,
    VT_NAME = 8
  };
  uint64_t base_address() const {
    return GetField<uint64_t>(VT_BASE_ADDRESS, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_BASE_ADDRESS, 8) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct KernelModuleBuilder {
  typedef KernelModule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base_address(uint64_t base_address) {
    fbb_.AddElement<uint64_t>(KernelModule::VT_BASE_ADDRESS, base_address, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(KernelModule::VT_SIZE, size, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(KernelModule::VT_NAME, name);
  }
  explicit KernelModuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KernelModule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KernelModule>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KernelModule> CreateKernelModule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t base_address = 0,
    uint32_t size = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  KernelModuleBuilder builder_(_fbb);
  builder_.add_base_address(base_address);
  builder_.add_name(name);
  builder_.add_size(size);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KernelModule> CreateKernelModuleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t base_address = 0,
    uint32_t size = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Anticheat::CreateKernelModule(
      _fbb,
      base_address,
      size,
      name__);
}

struct KernelModuleList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KernelModuleListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODULES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::KernelModule>> *modules() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::KernelModule>> *>(VT_MODULES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODULES) &&
           verifier.VerifyVector(modules()) &&
           verifier.VerifyVectorOfTables(modules()) &&
           verifier.EndTable();
  }
};

struct KernelModuleListBuilder {
  typedef KernelModuleList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_modules(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::KernelModule>>> modules) {
    fbb_.AddOffset(KernelModuleList::VT_MODULES, modules);
  }
  explicit KernelModuleListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KernelModuleList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KernelModuleList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KernelModuleList> CreateKernelModuleList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::KernelModule>>> modules = 0) {
  KernelModuleListBuilder builder_(_fbb);
  builder_.add_modules(modules);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KernelModuleList> CreateKernelModuleListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Anticheat::KernelModule>> *modules = nullptr) {
  auto modules__ = modules ? _fbb.CreateVector<::flatbuffers::Offset<Anticheat::KernelModule>>(*modules) : 0;
  return Anticheat::CreateKernelModuleList(
      _fbb,
      modules__);
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_KERNELMODULES_ANTICHEAT_H_
