// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGE_H_
#define FLATBUFFERS_GENERATED_MESSAGE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct MessageHeader;
struct MessageHeaderBuilder;

struct MessageHeader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageHeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_BODY_SIZE = 6,
    VT_IS_SYSTEM = 8
  };
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint64_t body_size() const {
    return GetField<uint64_t>(VT_BODY_SIZE, 0);
  }
  bool is_system() const {
    return GetField<uint8_t>(VT_IS_SYSTEM, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint64_t>(verifier, VT_BODY_SIZE, 8) &&
           VerifyField<uint8_t>(verifier, VT_IS_SYSTEM, 1) &&
           verifier.EndTable();
  }
};

struct MessageHeaderBuilder {
  typedef MessageHeader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(MessageHeader::VT_TYPE, type, 0);
  }
  void add_body_size(uint64_t body_size) {
    fbb_.AddElement<uint64_t>(MessageHeader::VT_BODY_SIZE, body_size, 0);
  }
  void add_is_system(bool is_system) {
    fbb_.AddElement<uint8_t>(MessageHeader::VT_IS_SYSTEM, static_cast<uint8_t>(is_system), 0);
  }
  explicit MessageHeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MessageHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MessageHeader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MessageHeader> CreateMessageHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t type = 0,
    uint64_t body_size = 0,
    bool is_system = false) {
  MessageHeaderBuilder builder_(_fbb);
  builder_.add_body_size(body_size);
  builder_.add_is_system(is_system);
  builder_.add_type(type);
  return builder_.Finish();
}

inline const MessageHeader *GetMessageHeader(const void *buf) {
  return ::flatbuffers::GetRoot<MessageHeader>(buf);
}

inline const MessageHeader *GetSizePrefixedMessageHeader(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MessageHeader>(buf);
}

template <bool B = false>
inline bool VerifyMessageHeaderBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<MessageHeader>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMessageHeaderBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<MessageHeader>(nullptr);
}

inline void FinishMessageHeaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MessageHeader> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageHeaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MessageHeader> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_MESSAGE_H_
