// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTECTEDPROCESS_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_PROTECTEDPROCESS_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct ProcessModule;
struct ProcessModuleBuilder;

struct ProtectedProcess;
struct ProtectedProcessBuilder;

struct ProtectedProcessList;
struct ProtectedProcessListBuilder;

struct ProcessModule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProcessModuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE_ADDRESS = 4,
    VT_SIZE = 6,
    VT_NAME = 8,
    VT_HASH = 10,
    VT_FULL_PATH = 12
  };
  uint64_t base_address() const {
    return GetField<uint64_t>(VT_BASE_ADDRESS, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<uint8_t> *hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HASH);
  }
  const ::flatbuffers::String *full_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FULL_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_BASE_ADDRESS, 8) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_HASH) &&
           verifier.VerifyVector(hash()) &&
           VerifyOffset(verifier, VT_FULL_PATH) &&
           verifier.VerifyString(full_path()) &&
           verifier.EndTable();
  }
};

struct ProcessModuleBuilder {
  typedef ProcessModule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base_address(uint64_t base_address) {
    fbb_.AddElement<uint64_t>(ProcessModule::VT_BASE_ADDRESS, base_address, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(ProcessModule::VT_SIZE, size, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(ProcessModule::VT_NAME, name);
  }
  void add_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash) {
    fbb_.AddOffset(ProcessModule::VT_HASH, hash);
  }
  void add_full_path(::flatbuffers::Offset<::flatbuffers::String> full_path) {
    fbb_.AddOffset(ProcessModule::VT_FULL_PATH, full_path);
  }
  explicit ProcessModuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ProcessModule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ProcessModule>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ProcessModule> CreateProcessModule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t base_address = 0,
    uint32_t size = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash = 0,
    ::flatbuffers::Offset<::flatbuffers::String> full_path = 0) {
  ProcessModuleBuilder builder_(_fbb);
  builder_.add_base_address(base_address);
  builder_.add_full_path(full_path);
  builder_.add_hash(hash);
  builder_.add_name(name);
  builder_.add_size(size);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ProcessModule> CreateProcessModuleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t base_address = 0,
    uint32_t size = 0,
    const char *name = nullptr,
    const std::vector<uint8_t> *hash = nullptr,
    const char *full_path = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto hash__ = hash ? _fbb.CreateVector<uint8_t>(*hash) : 0;
  auto full_path__ = full_path ? _fbb.CreateString(full_path) : 0;
  return Anticheat::CreateProcessModule(
      _fbb,
      base_address,
      size,
      name__,
      hash__,
      full_path__);
}

struct ProtectedProcess FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProtectedProcessBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROCESS_ID = 4,
    VT_MODULES = 6
  };
  uint32_t process_id() const {
    return GetField<uint32_t>(VT_PROCESS_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProcessModule>> *modules() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProcessModule>> *>(VT_MODULES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PROCESS_ID, 4) &&
           VerifyOffset(verifier, VT_MODULES) &&
           verifier.VerifyVector(modules()) &&
           verifier.VerifyVectorOfTables(modules()) &&
           verifier.EndTable();
  }
};

struct ProtectedProcessBuilder {
  typedef ProtectedProcess Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_process_id(uint32_t process_id) {
    fbb_.AddElement<uint32_t>(ProtectedProcess::VT_PROCESS_ID, process_id, 0);
  }
  void add_modules(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProcessModule>>> modules) {
    fbb_.AddOffset(ProtectedProcess::VT_MODULES, modules);
  }
  explicit ProtectedProcessBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ProtectedProcess> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ProtectedProcess>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ProtectedProcess> CreateProtectedProcess(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t process_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProcessModule>>> modules = 0) {
  ProtectedProcessBuilder builder_(_fbb);
  builder_.add_modules(modules);
  builder_.add_process_id(process_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ProtectedProcess> CreateProtectedProcessDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t process_id = 0,
    const std::vector<::flatbuffers::Offset<Anticheat::ProcessModule>> *modules = nullptr) {
  auto modules__ = modules ? _fbb.CreateVector<::flatbuffers::Offset<Anticheat::ProcessModule>>(*modules) : 0;
  return Anticheat::CreateProtectedProcess(
      _fbb,
      process_id,
      modules__);
}

struct ProtectedProcessList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProtectedProcessListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROCESSES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProtectedProcess>> *processes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProtectedProcess>> *>(VT_PROCESSES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROCESSES) &&
           verifier.VerifyVector(processes()) &&
           verifier.VerifyVectorOfTables(processes()) &&
           verifier.EndTable();
  }
};

struct ProtectedProcessListBuilder {
  typedef ProtectedProcessList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_processes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProtectedProcess>>> processes) {
    fbb_.AddOffset(ProtectedProcessList::VT_PROCESSES, processes);
  }
  explicit ProtectedProcessListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ProtectedProcessList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ProtectedProcessList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ProtectedProcessList> CreateProtectedProcessList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::ProtectedProcess>>> processes = 0) {
  ProtectedProcessListBuilder builder_(_fbb);
  builder_.add_processes(processes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ProtectedProcessList> CreateProtectedProcessListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Anticheat::ProtectedProcess>> *processes = nullptr) {
  auto processes__ = processes ? _fbb.CreateVector<::flatbuffers::Offset<Anticheat::ProtectedProcess>>(*processes) : 0;
  return Anticheat::CreateProtectedProcessList(
      _fbb,
      processes__);
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_PROTECTEDPROCESS_ANTICHEAT_H_
