// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REQUEST_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_REQUEST_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct PingRequest;
struct PingRequestBuilder;

enum RequestId : uint8_t {
  RequestId_Ping = 0,
  RequestId_ExampleCheckResult = 1,
  RequestId_ClientTimestampResult = 2,
  RequestId_KernelModuleListResult = 3,
  RequestId_EventBatchResult = 4,
  RequestId_ThreadListResult = 5,
  RequestId_MIN = RequestId_Ping,
  RequestId_MAX = RequestId_ThreadListResult
};

inline const RequestId (&EnumValuesRequestId())[6] {
  static const RequestId values[] = {
    RequestId_Ping,
    RequestId_ExampleCheckResult,
    RequestId_ClientTimestampResult,
    RequestId_KernelModuleListResult,
    RequestId_EventBatchResult,
    RequestId_ThreadListResult
  };
  return values;
}

inline const char * const *EnumNamesRequestId() {
  static const char * const names[7] = {
    "Ping",
    "ExampleCheckResult",
    "ClientTimestampResult",
    "KernelModuleListResult",
    "EventBatchResult",
    "ThreadListResult",
    nullptr
  };
  return names;
}

inline const char *EnumNameRequestId(RequestId e) {
  if (::flatbuffers::IsOutRange(e, RequestId_Ping, RequestId_ThreadListResult)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRequestId()[index];
}

struct PingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PingRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct PingRequestBuilder {
  typedef PingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(PingRequest::VT_TIMESTAMP, timestamp, 0);
  }
  explicit PingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PingRequest> CreatePingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0) {
  PingRequestBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  return builder_.Finish();
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_REQUEST_ANTICHEAT_H_
