// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESPONSE_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_RESPONSE_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct PongResponse;
struct PongResponseBuilder;

enum ResponseId : uint8_t {
  ResponseId_Pong = 0,
  ResponseId_MIN = ResponseId_Pong,
  ResponseId_MAX = ResponseId_Pong
};

inline const ResponseId (&EnumValuesResponseId())[1] {
  static const ResponseId values[] = {
    ResponseId_Pong
  };
  return values;
}

inline const char * const *EnumNamesResponseId() {
  static const char * const names[2] = {
    "Pong",
    nullptr
  };
  return names;
}

inline const char *EnumNameResponseId(ResponseId e) {
  if (::flatbuffers::IsOutRange(e, ResponseId_Pong, ResponseId_Pong)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResponseId()[index];
}

struct PongResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PongResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_TIMESTAMP = 4,
    VT_SERVER_TIMESTAMP = 6
  };
  uint64_t client_timestamp() const {
    return GetField<uint64_t>(VT_CLIENT_TIMESTAMP, 0);
  }
  uint64_t server_timestamp() const {
    return GetField<uint64_t>(VT_SERVER_TIMESTAMP, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct PongResponseBuilder {
  typedef PongResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_timestamp(uint64_t client_timestamp) {
    fbb_.AddElement<uint64_t>(PongResponse::VT_CLIENT_TIMESTAMP, client_timestamp, 0);
  }
  void add_server_timestamp(uint64_t server_timestamp) {
    fbb_.AddElement<uint64_t>(PongResponse::VT_SERVER_TIMESTAMP, server_timestamp, 0);
  }
  explicit PongResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PongResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PongResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PongResponse> CreatePongResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t client_timestamp = 0,
    uint64_t server_timestamp = 0) {
  PongResponseBuilder builder_(_fbb);
  builder_.add_server_timestamp(server_timestamp);
  builder_.add_client_timestamp(client_timestamp);
  return builder_.Finish();
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_RESPONSE_ANTICHEAT_H_
