// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIGNATURE_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_SIGNATURE_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct EmbeddedSignature;
struct EmbeddedSignatureBuilder;

struct CatalogSignature;
struct CatalogSignatureBuilder;

struct ImageSignatureCheckRequest;
struct ImageSignatureCheckRequestBuilder;

struct ImageSignatureCheckResult;
struct ImageSignatureCheckResultBuilder;

enum SignatureData : uint8_t {
  SignatureData_NONE = 0,
  SignatureData_EmbeddedSignature = 1,
  SignatureData_CatalogSignature = 2,
  SignatureData_MIN = SignatureData_NONE,
  SignatureData_MAX = SignatureData_CatalogSignature
};

inline const SignatureData (&EnumValuesSignatureData())[3] {
  static const SignatureData values[] = {
    SignatureData_NONE,
    SignatureData_EmbeddedSignature,
    SignatureData_CatalogSignature
  };
  return values;
}

inline const char * const *EnumNamesSignatureData() {
  static const char * const names[4] = {
    "NONE",
    "EmbeddedSignature",
    "CatalogSignature",
    nullptr
  };
  return names;
}

inline const char *EnumNameSignatureData(SignatureData e) {
  if (::flatbuffers::IsOutRange(e, SignatureData_NONE, SignatureData_CatalogSignature)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSignatureData()[index];
}

template<typename T> struct SignatureDataTraits {
  static const SignatureData enum_value = SignatureData_NONE;
};

template<> struct SignatureDataTraits<Anticheat::EmbeddedSignature> {
  static const SignatureData enum_value = SignatureData_EmbeddedSignature;
};

template<> struct SignatureDataTraits<Anticheat::CatalogSignature> {
  static const SignatureData enum_value = SignatureData_CatalogSignature;
};

template <bool B = false>
bool VerifySignatureData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SignatureData type);
template <bool B = false>
bool VerifySignatureDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct EmbeddedSignature FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmbeddedSignatureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PKCS7 = 4,
    VT_AUTHENTICODE_HASH = 6
  };
  const ::flatbuffers::Vector<uint8_t> *pkcs7() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PKCS7);
  }
  const ::flatbuffers::Vector<uint8_t> *authenticode_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_AUTHENTICODE_HASH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PKCS7) &&
           verifier.VerifyVector(pkcs7()) &&
           VerifyOffset(verifier, VT_AUTHENTICODE_HASH) &&
           verifier.VerifyVector(authenticode_hash()) &&
           verifier.EndTable();
  }
};

struct EmbeddedSignatureBuilder {
  typedef EmbeddedSignature Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pkcs7(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pkcs7) {
    fbb_.AddOffset(EmbeddedSignature::VT_PKCS7, pkcs7);
  }
  void add_authenticode_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> authenticode_hash) {
    fbb_.AddOffset(EmbeddedSignature::VT_AUTHENTICODE_HASH, authenticode_hash);
  }
  explicit EmbeddedSignatureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmbeddedSignature> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmbeddedSignature>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmbeddedSignature> CreateEmbeddedSignature(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pkcs7 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> authenticode_hash = 0) {
  EmbeddedSignatureBuilder builder_(_fbb);
  builder_.add_authenticode_hash(authenticode_hash);
  builder_.add_pkcs7(pkcs7);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EmbeddedSignature> CreateEmbeddedSignatureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *pkcs7 = nullptr,
    const std::vector<uint8_t> *authenticode_hash = nullptr) {
  auto pkcs7__ = pkcs7 ? _fbb.CreateVector<uint8_t>(*pkcs7) : 0;
  auto authenticode_hash__ = authenticode_hash ? _fbb.CreateVector<uint8_t>(*authenticode_hash) : 0;
  return Anticheat::CreateEmbeddedSignature(
      _fbb,
      pkcs7__,
      authenticode_hash__);
}

struct CatalogSignature FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CatalogSignatureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AUTHENTICODE_HASH = 4,
    VT_CATALOG_PKCS7 = 6
  };
  const ::flatbuffers::Vector<uint8_t> *authenticode_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_AUTHENTICODE_HASH);
  }
  const ::flatbuffers::Vector<uint8_t> *catalog_pkcs7() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CATALOG_PKCS7);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_AUTHENTICODE_HASH) &&
           verifier.VerifyVector(authenticode_hash()) &&
           VerifyOffset(verifier, VT_CATALOG_PKCS7) &&
           verifier.VerifyVector(catalog_pkcs7()) &&
           verifier.EndTable();
  }
};

struct CatalogSignatureBuilder {
  typedef CatalogSignature Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_authenticode_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> authenticode_hash) {
    fbb_.AddOffset(CatalogSignature::VT_AUTHENTICODE_HASH, authenticode_hash);
  }
  void add_catalog_pkcs7(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> catalog_pkcs7) {
    fbb_.AddOffset(CatalogSignature::VT_CATALOG_PKCS7, catalog_pkcs7);
  }
  explicit CatalogSignatureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CatalogSignature> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CatalogSignature>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CatalogSignature> CreateCatalogSignature(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> authenticode_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> catalog_pkcs7 = 0) {
  CatalogSignatureBuilder builder_(_fbb);
  builder_.add_catalog_pkcs7(catalog_pkcs7);
  builder_.add_authenticode_hash(authenticode_hash);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CatalogSignature> CreateCatalogSignatureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *authenticode_hash = nullptr,
    const std::vector<uint8_t> *catalog_pkcs7 = nullptr) {
  auto authenticode_hash__ = authenticode_hash ? _fbb.CreateVector<uint8_t>(*authenticode_hash) : 0;
  auto catalog_pkcs7__ = catalog_pkcs7 ? _fbb.CreateVector<uint8_t>(*catalog_pkcs7) : 0;
  return Anticheat::CreateCatalogSignature(
      _fbb,
      authenticode_hash__,
      catalog_pkcs7__);
}

struct ImageSignatureCheckRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImageSignatureCheckRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FULL_PATH = 4
  };
  const ::flatbuffers::String *full_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FULL_PATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FULL_PATH) &&
           verifier.VerifyString(full_path()) &&
           verifier.EndTable();
  }
};

struct ImageSignatureCheckRequestBuilder {
  typedef ImageSignatureCheckRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_full_path(::flatbuffers::Offset<::flatbuffers::String> full_path) {
    fbb_.AddOffset(ImageSignatureCheckRequest::VT_FULL_PATH, full_path);
  }
  explicit ImageSignatureCheckRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ImageSignatureCheckRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ImageSignatureCheckRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ImageSignatureCheckRequest> CreateImageSignatureCheckRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> full_path = 0) {
  ImageSignatureCheckRequestBuilder builder_(_fbb);
  builder_.add_full_path(full_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ImageSignatureCheckRequest> CreateImageSignatureCheckRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *full_path = nullptr) {
  auto full_path__ = full_path ? _fbb.CreateString(full_path) : 0;
  return Anticheat::CreateImageSignatureCheckRequest(
      _fbb,
      full_path__);
}

struct ImageSignatureCheckResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImageSignatureCheckResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FULL_PATH = 4,
    VT_DATA_TYPE = 6,
    VT_DATA = 8
  };
  const ::flatbuffers::String *full_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FULL_PATH);
  }
  Anticheat::SignatureData data_type() const {
    return static_cast<Anticheat::SignatureData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const Anticheat::EmbeddedSignature *data_as_EmbeddedSignature() const {
    return data_type() == Anticheat::SignatureData_EmbeddedSignature ? static_cast<const Anticheat::EmbeddedSignature *>(data()) : nullptr;
  }
  const Anticheat::CatalogSignature *data_as_CatalogSignature() const {
    return data_type() == Anticheat::SignatureData_CatalogSignature ? static_cast<const Anticheat::CatalogSignature *>(data()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FULL_PATH) &&
           verifier.VerifyString(full_path()) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifySignatureData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Anticheat::EmbeddedSignature *ImageSignatureCheckResult::data_as<Anticheat::EmbeddedSignature>() const {
  return data_as_EmbeddedSignature();
}

template<> inline const Anticheat::CatalogSignature *ImageSignatureCheckResult::data_as<Anticheat::CatalogSignature>() const {
  return data_as_CatalogSignature();
}

struct ImageSignatureCheckResultBuilder {
  typedef ImageSignatureCheckResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_full_path(::flatbuffers::Offset<::flatbuffers::String> full_path) {
    fbb_.AddOffset(ImageSignatureCheckResult::VT_FULL_PATH, full_path);
  }
  void add_data_type(Anticheat::SignatureData data_type) {
    fbb_.AddElement<uint8_t>(ImageSignatureCheckResult::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(ImageSignatureCheckResult::VT_DATA, data);
  }
  explicit ImageSignatureCheckResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ImageSignatureCheckResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ImageSignatureCheckResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ImageSignatureCheckResult> CreateImageSignatureCheckResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> full_path = 0,
    Anticheat::SignatureData data_type = Anticheat::SignatureData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  ImageSignatureCheckResultBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_full_path(full_path);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ImageSignatureCheckResult> CreateImageSignatureCheckResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *full_path = nullptr,
    Anticheat::SignatureData data_type = Anticheat::SignatureData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  auto full_path__ = full_path ? _fbb.CreateString(full_path) : 0;
  return Anticheat::CreateImageSignatureCheckResult(
      _fbb,
      full_path__,
      data_type,
      data);
}

template <bool B>
inline bool VerifySignatureData(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SignatureData type) {
  switch (type) {
    case SignatureData_NONE: {
      return true;
    }
    case SignatureData_EmbeddedSignature: {
      auto ptr = reinterpret_cast<const Anticheat::EmbeddedSignature *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SignatureData_CatalogSignature: {
      auto ptr = reinterpret_cast<const Anticheat::CatalogSignature *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifySignatureDataVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySignatureData(
        verifier,  values->Get(i), types->GetEnum<SignatureData>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_SIGNATURE_ANTICHEAT_H_
