// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYSTEM_SYSTEM_H_
#define FLATBUFFERS_GENERATED_SYSTEM_SYSTEM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace System {

struct HbPingRequest;
struct HbPingRequestBuilder;

struct HbPongRequest;
struct HbPongRequestBuilder;

enum MessageId : uint8_t {
  MessageId_HbPing = 0,
  MessageId_HbPong = 1,
  MessageId_MIN = MessageId_HbPing,
  MessageId_MAX = MessageId_HbPong
};

inline const MessageId (&EnumValuesMessageId())[2] {
  static const MessageId values[] = {
    MessageId_HbPing,
    MessageId_HbPong
  };
  return values;
}

inline const char * const *EnumNamesMessageId() {
  static const char * const names[3] = {
    "HbPing",
    "HbPong",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageId(MessageId e) {
  if (::flatbuffers::IsOutRange(e, MessageId_HbPing, MessageId_HbPong)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageId()[index];
}

struct HbPingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HbPingRequestBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct HbPingRequestBuilder {
  typedef HbPingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit HbPingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HbPingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HbPingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HbPingRequest> CreateHbPingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  HbPingRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct HbPongRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HbPongRequestBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct HbPongRequestBuilder {
  typedef HbPongRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit HbPongRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HbPongRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HbPongRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HbPongRequest> CreateHbPongRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  HbPongRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

}  // namespace System

#endif  // FLATBUFFERS_GENERATED_SYSTEM_SYSTEM_H_
