// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_THREAD_ANTICHEAT_H_
#define FLATBUFFERS_GENERATED_THREAD_ANTICHEAT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Anticheat {

struct Thread;
struct ThreadBuilder;

struct ThreadList;
struct ThreadListBuilder;

struct Thread FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ThreadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_THREAD_ID = 4,
    VT_START_ADDRESS = 6
  };
  uint32_t thread_id() const {
    return GetField<uint32_t>(VT_THREAD_ID, 0);
  }
  uint64_t start_address() const {
    return GetField<uint64_t>(VT_START_ADDRESS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_THREAD_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_START_ADDRESS, 8) &&
           verifier.EndTable();
  }
};

struct ThreadBuilder {
  typedef Thread Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_thread_id(uint32_t thread_id) {
    fbb_.AddElement<uint32_t>(Thread::VT_THREAD_ID, thread_id, 0);
  }
  void add_start_address(uint64_t start_address) {
    fbb_.AddElement<uint64_t>(Thread::VT_START_ADDRESS, start_address, 0);
  }
  explicit ThreadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Thread> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Thread>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Thread> CreateThread(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t thread_id = 0,
    uint64_t start_address = 0) {
  ThreadBuilder builder_(_fbb);
  builder_.add_start_address(start_address);
  builder_.add_thread_id(thread_id);
  return builder_.Finish();
}

struct ThreadList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ThreadListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_THREADS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Thread>> *threads() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Thread>> *>(VT_THREADS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_THREADS) &&
           verifier.VerifyVector(threads()) &&
           verifier.VerifyVectorOfTables(threads()) &&
           verifier.EndTable();
  }
};

struct ThreadListBuilder {
  typedef ThreadList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_threads(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Thread>>> threads) {
    fbb_.AddOffset(ThreadList::VT_THREADS, threads);
  }
  explicit ThreadListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ThreadList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ThreadList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ThreadList> CreateThreadList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Anticheat::Thread>>> threads = 0) {
  ThreadListBuilder builder_(_fbb);
  builder_.add_threads(threads);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ThreadList> CreateThreadListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Anticheat::Thread>> *threads = nullptr) {
  auto threads__ = threads ? _fbb.CreateVector<::flatbuffers::Offset<Anticheat::Thread>>(*threads) : 0;
  return Anticheat::CreateThreadList(
      _fbb,
      threads__);
}

}  // namespace Anticheat

#endif  // FLATBUFFERS_GENERATED_THREAD_ANTICHEAT_H_
